spring:
  application:
    name: driver-service
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092

server:
  port: 8089

eureka:
  client:
    service-url-defaultZone: http://localhost:8761/eureka