server:
  port: 8765

spring:
  application:
    name: gateway-api
  security:
    oauth2:
      client:
#        registration:
#          keycloak:
#            provider: keycloak
#            client-id: gateway-client
#            client-secret: eLANPRBugsswihgAnaAgiiKfRG4r1XzR
#            authorization-grant-type: authorization_code
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/my-realm
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_LAST
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
        - id: auth
          uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/token
          predicates:
            - Path=/openid-connect/**
          filters:
            - RewritePath=/openid-connect,/realms/my-realm/protocol/openid-connect

        - id: portal-service
          uri: http://localhost:8087
          predicates:
            - Path=/portal/**
          filters:
            - RewritePath=/portal, /

        - id: logist-service
          uri: lb://logist-service
          predicates:
            - Path=/logist

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/driver

        - id: dwh-service
          uri: lb://dwh-service
          predicates:
            - Path=/dwh
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  auth-server-url: http://localhost:8080
  realm: my-realm
  client: gateway-client
  client-secret: eLANPRBugsswihgAnaAgiiKfRG4r1XzR
  username: admin
  password: qwe123
  auth-path: /realms/my-realm/protocol/openid-connect/token
