server:
  port: 8765

spring:
  application:
    name: gateway-api
  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_LAST
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
        - id: auth
          uri: http://localhost:8080/realms/my-realm/protocol/openid-connect/token
          predicates:
            - Path=/openid-connect/**
          filters:
            - RewritePath=/openid-connect,/realms/my-realm/protocol/openid-connect

        - id: portal-service
          uri: http://localhost:8087
          predicates:
            - Path=/portal/**
          filters:
            - RewritePath=/portal, /

        - id: logist-service
          uri: http://localhost:8088
          predicates:
            - Path=/logist/**
          filters:
            - RewritePath=/logist, /

        - id: driver-service
          uri: http://localhost:8089
          predicates:
            - Path=/driver/**
          filters:
            - RewritePath=/driver, /

        - id: dwh-service
          uri: http://localhost:8090
          predicates:
            - Path=/dwh/**
          filters:
            - RewritePath=/dwh, /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  auth-server-url: http://localhost:8080
  realm: my-realm
  client: gateway-client
  client-secret: eLANPRBugsswihgAnaAgiiKfRG4r1XzR
  username: admin
  password: qwe123
  auth-path: /realms/my-realm/protocol/openid-connect/token
